# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Trang Chủ
    url: /#top
    weight: 10
  - name: Tính năng
    url: /#features
    weight: 20
  - name: Giải pháp
    url: /#solutions
    weight: 30
  - name: Blog
    url: blog/
    weight: 40
  - name: Liên Hệ
    url: lien-he/
    weight: 50

