# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Organization
    local_business_type: 'Cơ khí'
    org_name: 'Cơ Khí Long Kim AC'
    description: 'Cơ khí Tây Ninh, chuyên gia công cơ khí, lắp đặt, sửa chữa máy móc, thiết bị công nghiệp tại Long Kim AC.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo.jpg"
    button:
      enable: true
      text: "Liên Hệ Ngay"
      url: "lien-he/"
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© {year} Long Kim AC Company'

# Localization
locale:
  date_format: '02/01/2006'
  time_format: '15:04'
